<?php

namespace AppBundle\Repository;

/**
 * PropertyDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyDayRepository extends \Doctrine\ORM\EntityRepository
{
}
